myproject/ModalsDateBase/urls.py
from django.urls import path
from .views import News_list, News_Detail, SearchNews, create_post, search, EditPost, DeletPost, subscriptions

urlpatterns = [
    path('', News_list.as_view(), name='news_list'),
    path('search/', SearchNews.as_view(), name='search'),
    path('<int:pk>/', News_Detail.as_view(), name='news_detail'),
    path('create/',create_post, name='create_post'),
    path('<int:pk>/update', EditPost.as_view(), name='update_post'),
    path('<int:pk>/delete', DeletPost.as_view(),name='delete_post'),
    path('subscriptions/', subscriptions, name='subscriptions'),
    # path('createAuthor/',save(), name='author_create')
]

myproject/accounts/urls.py
from django.urls import path
from .forms import SignIn

urlpatterns = [
    path('signup/', SignIn.as_view(),name='sign')
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('ModalsDateBase.urls')),
    path('accounts/', include('allauth.urls')),
    path('index/', IndexView.as_view()),
]

myproject/ModalsDateBase/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save, m2m_changed
from django.dispatch import receiver
from django.core.mail import EmailMultiAlternatives

class Author(models.Model):
    """
        This class is realizate User-Select - rating and name    
    """
    
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    rating = models.IntegerField(default=0)
    
    def update_rating(self):
        full_rating = 0
        full_coments_rating = 0
        full_post_rating = 0
    
        post = Post.objects.filter(author=self)
        for pos in post:
            full_rating += pos.raiting_post
            
        comments = Comment.objects.filter(user_comment=self.user)
        for com in comments:
            full_coments_rating += com.rating_comment
            
        posts_comment = Comment.objects.filter(post_comment__author=self)
        for pos_com in posts_comment:
            full_post_rating += pos_com.rating_comment
            
        print(full_rating)
        print(full_coments_rating)
        print(full_post_rating)    
        
        
        self.rating = full_coments_rating + full_post_rating + full_rating * 3
        self.save()
            
            
class Catigory(models.Model):
    """
        subjects for news/post, this class is stores sub
    """
    category = models.CharField(max_length=50, unique=True)
    
    def __str__(self) -> str:
        return self.category
    
    
class Post(models.Model):
    """
        This model should contain articles and news that are created by users. Each object can have one or more categories
    """
    
    title = models.CharField(max_length=50)
    text_post = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True)
    content_post = models.ForeignKey(to='Catigory',related_name='post_category', on_delete=models.CASCADE, null=True)
    time_post = models.DateTimeField(auto_now_add=True)
    raiting_post = models.IntegerField(default=0)
    
    
    def get_absolute_url(self):
        return reverse('news_detail', kwargs={'pk': self.pk})
    
    #preview text
    def preview(self):
        text_preview = self.text_post[:124]
        
        if len(self.text_post) > 124:
            text_preview += '...'

        return text_preview
    
        #this method  rating post on the one point
    def like(self):
        self.raiting_post += 1
        self.save()
    
    #this method reduces rating post on the one point
    def dislike(self):  
        self.raiting_post -= 1
        self.save()
        
    def best_post(self):
        post_ratings = list(Post.objects.filter(author=self).order_by('-raiting_post').values_list('title', Post.preview()))
    
        print(post_ratings[0])
        
        
    def __str__(self):
        return self.title
     
# @receiver(m2m_changed, sender=Post.author)
# def post_created(instance, action, **kwargs):
#     if action == 'post_add':
#         print("New post added to category:")
#         categories = instance.categories.all()
#         emails = User.objects.filter(subscribers__category__in=categories).values_list('email', flat=True)
        
#         subject = f'New post: {instance.title}'

#         text_content = (
#             f'Post: {instance.title}\n'
#             f'http://127.0.0.1:8000{instance.get_absolute_url()}'
#         )
#         html_content = (
#             f'{instance.title}<br>'
#             f'<a href="http://127.0.0.1{instance.get_absolute_url()}">'
#         )
    
#         for email in emails:
#             msg = EmailMultiAlternatives(subject, text_content, None, [email])
#             msg.send()
                   
class PostCatigory(models.Model):
    """
        Connecting to models Post and Catigory
    """
    conect_catigory = models.ForeignKey(Catigory,on_delete=models.CASCADE)
    conect_post = models.ForeignKey(Post, on_delete=models.CASCADE)

class Comment(models.Model):
    """
        Comment in post, user can writes text under post
    """
    post_comment = models.ForeignKey(Post, on_delete=models.CASCADE)
    user_comment = models.ForeignKey(User, on_delete=models.CASCADE)
    text_comment = models.TextField(max_length=100)
    data_time_comment = models.DateTimeField(auto_now_add=True)
    rating_comment = models.IntegerField(default=0)
    
    #this method  rating comment on the one point
    def like(self):
        self.rating_comment += 1
        self.save()
        
    #this method reduces rating comment on the one point
    def dislike(self):
        self.rating_comment -=1
        self.save()
        
        
class Best_rating_user(models.Model):
    
    def print_best_users(self):
        user_ratings = list(Author.objects.all().order_by('-rating').values_list('user__username', 'rating'))
    
        print(user_ratings[0])
    
class Subscription(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='subcribers' )
    category = models.ForeignKey(to=Catigory, on_delete=models.CASCADE, related_name='subcribers')

myproject/ModalsDateBase/forms.py
from django import forms
from .models import Post, Catigory, Author
import datetime
from django.http import request


class CreatePost(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = [
            'title',
           'text_post',
           'content_post',
        ]
    
    # def __init__(self, *args, **kwargs):
    #     self.author = kwargs.pop('author', None)
    #     super(CreatePost, self).__init__(*args, **kwargs)
    #     if self.author:
    #         self.instance.author = self.author

    # def save(self, commit=True):
    #     instance = super(CreatePost, self).save(commit=False)
    #     if not instance.author_id:
    #         instance.author = self.author
    #     if commit:
    #         instance.save()
    #     return instance
    
class UpdatePost(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            
           'text_post',
           'content_post'
        ]
        
class PostFormFilter(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = [
            'title',
            'content_post',
        ]
        
    def filter_posts(self):
        title = self.cleaned_data.get('title')
        content_post = self.cleaned_data.get('content_post')
        date = self.cleaned_data.get('date')

        posts = Post.objects.all()

        if title:
            posts = posts.filter(title__icontains=title)

        if content_post:
            posts = posts.filter(content_post__icontains=content_post)

        if date:
            posts = posts.filter(date__gte=date)

        return posts

myproject/ModalsDateBase/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from celery import shared_task
from django.views.generic import ListView,DetailView, UpdateView, DeleteView, View
from .models import Post, Author, Subscription
from datetime import datetime
from django.core.mail import send_mail,mail_admins
from django.http import HttpResponse, HttpResponseRedirect
from .filters import *
from .forms import CreatePost, PostFormFilter, UpdatePost
from django import forms
from django.http import request
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin , PermissionRequiredMixin
from django.contrib.auth.decorators import user_passes_test, login_required
from django.views.decorators.csrf import csrf_protect
from django.db.models import Exists, OuterRef
from myproject.tasks import send_messege_subscribers




class News_list(ListView):
    model = Post
    ordering = ''
    template_name = 'project.htm'
    context_object_name = 'post'
    paginate_by=10
    
    
    def check_title_exist(self, value):
        instance = PostFilter({'title': value}, queryset=Post.objects.all())
        
        exist = instance.qs.exists()
        
        return exist
    
    def get_queryset(self):
        queryset = super().get_queryset()
        self.form = PostFilter(self.request.GET, queryset)
        return self.form.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        return context
    
class SearchNews(ListView):
    model = Post
    ordering = ''
    template_name = 'search.html' 
    context_object_name = 'search'
    
    def get_queryset(self):
        queryset =  super().get_queryset()
        self.filterset = PostFilter(self.request.POST, queryset)
        return self.filterset.qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filterset"] = self.filterset
        return context
    
    def post(self, request, *args, **kwargs):
        # Handle POST request logic here
        # For example, perform form submission or other operations
        return self.get(request, *args, **kwargs)
        
    
class News_Detail(DetailView):
    model = Post
    ordering = 'text_post'
    template_name = 'detail.htm'
    context_object_name =  'one_post'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        return context

class EditPost(PermissionRequiredMixin,UpdateView):
    permission_required = ('ModalsDateBase.change_post')
    form_class = UpdatePost
    model = Post
    template_name = 'update_post.html'
    
class DeletPost(DeleteView):
    model = Post 
    success_url = reverse_lazy('news_list')
    template_name = 'delete_post.html'

def multiply(request):
    number = request.GET.get('number')
    multiplier = request.GET.get('multiplier')
    
    try:
       result = int(number) * int(multiplier)
       html = f"<html><body>{number}*{multiplier}={result}</body></html>"
    except (ValueError, TypeError):
        html = f"<html><body>Invalid input.</body></html>"

    return HttpResponse(html)

# def check_perm(user):
#     if user.has_perm('create_post'):
#         return True
#     else:
#         return False


def is_author(user):
    return user.groups.filter(name='authors').exists()


def create_post(request):
    if request.method == 'POST':
        form = CreatePost(request.POST)
        if form.is_valid():
            current_user = request.user
            author = Author.objects.get(user=current_user)
            post = form.save(commit=False)
            post.author = author
            post.save()
            send_messege_subscribers(post)
            return HttpResponseRedirect('/news/')
    else:
        form = CreatePost()
    return render(request, 'create_post.html', {'form': form})

def search(request):
    form = PostFormFilter()
    if request.method == 'POST':
        return HttpResponseRedirect('/news/')
        
        
    return render(request, 'search.html', {'form': form})


@login_required
@csrf_protect
def subscriptions(request):
    if request.method == 'POST':
        category_id = request.POST.get('category_id')
        category = Catigory.objects.get(id=category_id)
        action = request.POST.get('action')

        if action == 'subscribe':
            Subscription.objects.create(user=request.user, category=category)
        elif action == 'unsubscribe':
            Subscription.objects.filter(
                user=request.user,
                category=category,
            ).delete()

    categories_with_subscriptions = Catigory.objects.annotate(
        user_subscribed=Exists(
            Subscription.objects.filter(
                user=request.user,
                category=OuterRef('pk'),
            )
        )
    ).order_by('category')
    return render(
        request,
        'subscriptions.html',
        {'categories': categories_with_subscriptions},
    )
    

# def save():
#     author = Author.objects.create(user=request)
#     author.save()
        
#     send_mail (
#         subject='Thanks for singup',
#         message=f'Succes singup to user {author.username}',
#         recipient_list=[author.email],
#         from_email=None,
#     )
        
#     mail_admins(
#         subject='New User',
#         message=f'User {author.username} singup'
#     )
#     return render(
#         request,
#         'makeAuthor',
#         {'You Author': author},
#     )
    

myproject/ModalsDateBase/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default Title{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

myproject/ModalsDateBase/templates/create_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>
    <!-- Подключение стилей -->
    <link rel='stylesheet' href='{% static "style_createPost.css" %}'/>
</head>
<body>
    {% block content %}
    <h1 class='post1'>Create Post</h1>
    <form action='' method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Create Post'>
    </form>
    {% endblock %}
</body>
</html>

myproject/ModalsDateBase/templates/delete_post.html
{%block content%}
<h1>Delete Post</h1>
<form action='' method='post'>
    {% csrf_token %}
    <p>Удалить пост {{object.title}}?</p>
    <input type='submit' value='Delete'>
{% endblock %}

myproject/ModalsDateBase/templates/detail.htm
{% extends 'base.html' %}

{% block content %}
    <body>
        {% load custom_filter%}
        <h1> This Day is {{one_post|length}} Posts</h1>
        <h2> Post: {{one_post.title}} </h2>
        <h3> {{one_post.time_post|date:' d M Y T H:i'}}</h3>
        <h4>  - {{one_post.text_post|currency}}</h4>
            
    </body>
{% endblock %}

myproject/ModalsDateBase/templates/project.htm
{% extends 'base.html' %}
{% block content %}
{% load custom_filter%}
    <body>
        <h1> Wellcome back {{request.user}}</h>
        {%if perms.ModalsDateBase.add_post%}
        <a href="{% url 'create_post' %}"> Create post</a>
        {%endif%}
        <h1> This Page is {{post|length}} Posts</h1>
        {%for posts in post%}
        <a href= {% url 'news_detail' posts.id %}><h1>{{posts}}</h1></a>
        <h3>Author: {{posts.author.user}}</3>
        <h3> {{posts.time_post|date:'d M Y T H:i' }}
        <h4>  - {{posts.text_post|truncatechars:20|currency}}
            
            {%if posts.author.user == request.user%}
            <a href= {% url 'delete_post' posts.id%}>Delete post</a>
            
            {%endif%}
            {%if perms.ModalsDateBase.change_post%}
            {%if posts.author.user == request.user%}
            <a href= {% url 'update_post' posts.id%}>Update post</a>
            {%endif%}
            {%endif%}
        {%endfor%}
        <hr>
        {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
 
    {# Информация о текущей странице #}
    {{ page_obj.number }}
 
    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
 
    </body>
{% endblock %}

myproject/ModalsDateBase/templates/search.html
{% block content %}

  <!-- Optionally, you can display the applied filters -->
  <form action='' method='post'>
  {% if filterset %}
    <h3>Applied Filters:</h3>
    {{ filterset.form.as_p }}
      {% csrf_token %} 
    <input type='submit' value='search'/>
  {% endif %}
    </form>

  <h2>Search Results</h2>
  {% for post in search %}
  <p>{{ post.title }}</p>
  <p>{{ post.text_post }}</p>
  <hr>
{% endfor %}

        <hr>
        {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
 
    {# Информация о текущей странице #}
    {{ page_obj.number }}
 
    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
{%endblock content%}

myproject/ModalsDateBase/templates/subscriptions.html
{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.category }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}

myproject/ModalsDateBase/templates/update_post.html
{%block content%}
<h1>Update Post</h1>
<form action='' method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <input type='submit' value='Update Post'>
{% endblock %}